### PR TITLE
Functional Login Test

### PR DESCRIPTION
**Pull request by jaonoctus**

### CODE REVIEW

**Comment by Utwo** [comment]
Nice! 

There are some conflicts. Can you take a look?

**Comment by jaonoctus** [comment]
Sure!

**Comment by jaonoctus** [comment]
@Utwo I'm in a new job now, so I haven't had time to work this out before.

I did a rebase from af71d0d5273e1e4291b351af39f5ee3a66d9e6fc (last commit from your master branch). I think that you can merge it now :smile:

**Comment by Utwo** [comment]
Good luck on your new job!

**Pull request merged**
